#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat $1)"
requiredPattern="^(Feat|Refactor|Fix|Test|Chore|Doc|Style|Merge)\: .*$"
if ! [[ $message =~ $requiredPattern ]];
then
    echo "  ========================================"
    echo ""
    echo "    Feat|Refactor|Fix|Test|Chore|Doc|Style"
    echo "     Ex: Feat: descrição da mudança"
    echo ""
    echo "  ========================================"
    exit 1
fi