#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint

npm run testcommit

BRANCH=`git rev-parse --abbrev-ref HEAD`
PROTECTED_BRANCHES="^(main|master|development)"
# TIPO_BRANCHE="^(FIX|FEAT|REFACTOR)\/BTREE-\d+$"

if [[ "$BRANCH" =~ $PROTECTED_BRANCHES ]]
then
    echo "=================================================="
    echo ""
    echo "   A branch $BRANCH está bloqueada para commit"
    echo ""
    echo "=================================================" 
    exit 1
fi

# if [[ "$BRANCH" == $TIPO_BRANCHE ]]
# then
#     echo "  ================================================="

#     echo ""
#     echo "       Use o padão: <TIPO>/BTREE-<NUMERO_CARD>."
#     echo "                ex: FIX/BTREE-1234."
#     echo ""
#     echo " ==================================================" 
#     exit 1
# fi

exit 0